[2023-06-15T02:14:56.614+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: add_execution_entry_dag.create_table_task scheduled__2023-06-15T02:13:00+00:00 [queued]>
[2023-06-15T02:14:56.627+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: add_execution_entry_dag.create_table_task scheduled__2023-06-15T02:13:00+00:00 [queued]>
[2023-06-15T02:14:56.629+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T02:14:56.632+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-15T02:14:56.633+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T02:14:56.652+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_table_task> on 2023-06-15 02:13:00+00:00
[2023-06-15T02:14:56.662+0000] {standard_task_runner.py:55} INFO - Started process 775 to run task
[2023-06-15T02:14:56.688+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'add_execution_entry_dag', 'create_table_task', 'scheduled__2023-06-15T02:13:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/postgres.py', '--cfg-path', '/tmp/tmpdjo6gy3h']
[2023-06-15T02:14:56.694+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_table_task
[2023-06-15T02:14:56.902+0000] {task_command.py:389} INFO - Running <TaskInstance: add_execution_entry_dag.create_table_task scheduled__2023-06-15T02:13:00+00:00 [running]> on host 5bb6e3228243
[2023-06-15T02:14:57.002+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=add_execution_entry_dag
AIRFLOW_CTX_TASK_ID=create_table_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T02:13:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-15T02:13:00+00:00
[2023-06-15T02:14:57.019+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-06-15T02:14:57.034+0000] {sql.py:364} INFO - Running statement: CREATE TABLE IF NOT EXISTS postgres_table (execution_time TIMESTAMP), parameters: None
[2023-06-15T02:14:57.050+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres.py", line 14, in create_table_if_not_exists
    postgres_hook.run(create_table_query)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(postgres_table, 2200) already exists.

[2023-06-15T02:14:57.085+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=add_execution_entry_dag, task_id=create_table_task, execution_date=20230615T021300, start_date=20230615T021456, end_date=20230615T021457
[2023-06-15T02:14:57.113+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_table_task (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(postgres_table, 2200) already exists.
; 775)
[2023-06-15T02:14:57.134+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-15T02:14:57.168+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
